<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<?php require 'parts/search_box.php' ?>
	</div>
</div>

<?php if(isset($query)) { ?>
<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
	        <div class="panel-heading">
		        <h3 class="panel-title"><?php echo $this->translate('Search Results') ?> - <?php echo $query ?></h3>
	        </div>
	        <div class="panel-body">
	        </div>
        </div>
    </div>
</div>
<?php } ?>