<div class="row">
	<div class="col-md-6 col-md-offset-3">
        <?php require 'parts/search_box.php' ?>
	</div>
</div>

<?php
/** @var \Application\Model\SearchResults $results */
?>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
	        <div class="panel-heading">
		        <h3 class="panel-title"><?php echo $this->translate('Search Results') ?> - <?php echo $query ?><span style="float: right;">Total: <?= $results->getTotal() ?></span></h3>
	        </div>
	        <div class="panel-body row">
		        <?php foreach($results as $result) { ?>
			        <div class="col-sm-12 col-xs-12 col-md-4 col-lg-3">
				        <div class="thumbnail bootsnipp-thumb">
					        <div>
						        <p class="lead snip-title" title="<?= $result['title'] ?>">
							        <a href="<?= $result['url'] ?>"><?= $result['title'] ?></a>
						        </p>
					        </div>
					        <a href="<?= $result['url'] ?>">
						        <img src="<?= $result['thumbnail_240_url'] ?>" style="display: block;" height="240" width="320">
					        </a>

					        <div class="caption">
					        </div>
				        </div>
			        </div>
				<?php } ?>
	        </div>
        </div>
    </div>
</div>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
        <?php require 'parts/pagination.php' ?>
	</div>
</div>